### PR TITLE
Reduce default client cache time of random images

### PR DESCRIPTION
**Pull request by 22222**
The random Arnold pictures (and probably also the other, lesser pictures) are cached for too long.  One random Arnold picture per day is not enough.

This change would reduce the default client cache duration on random images from 24 hours to 5 seconds, without changing the cache duration for the endpoint that specifies the image id.

### CODE REVIEW

**Comment by seibar** [comment]
While I agree that more random Arnolds would be a good thing, I believe this will increase my hosting costs somewhat (though possibly the benefits to our country and the world will outweigh those costs).

What do you think about something like 10 minutes for the random cache, and increasing the by-id cache?

**Comment by 22222** [comment]
Seems fair.  Maybe the world can only handle so much Arnold diversity.  I increased the random cache duration to 10 minutes and the by-id one to 100 days.  But then I made one more change...

How about this for a crazy idea: what if the random image url is just a redirect to an actual image?

The the redirect can be cached for a shorter period of time (10 minutes), and it will redirect to the by-id url with a much longer cache duration (100 days).  So then if the user gets the same random Arnold picture, they'll get it from their cache instead of requesting it again.  As an added bonus, it makes it easier to discover the URL to a given Arnold picture.

The main downside is that requesting a random image for the first time results in two HTTP requests.  But other than that, there don't seem to be any major know disadvantages: https://stackoverflow.com/questions/1359115/what-are-the-implications-to-redirecting-images-behind-the-image-tag (because stackoverflow answers are never wrong).

**Comment by seibar** [comment]
I think the downside of multiple HTTP requests isn't too bad. The AWS compute instance cost is constant, whether its used or not, so as long as it doesn't require scaling up the instances (which I wouldn't anticipate), the app side shouldn't change. The variable costs are S3 storage and bandwidth, but those are very low (about $0.22 so far this month for S3 + data transfer).

At some point I want to refactor to take advantage of AWS Lambda, which will hopefully decrease costs quite a bit for the app side.

PR looks good. I tested it locally, and it seems to work.

☃

**Comment by seibar** [comment]
Increased arnold frequency is now deployed. http://www.arnold.fun/

**Pull request merged**
